import {
  ARYAN_PROFILE,
  PORTFOLIO_INFO,
  PROJECTS_DATA,
  NOTES_DATA,
  SKILLS_CATEGORIZED,
  RESUME_PROJECTS,
  RESUME_PROJECT_IDS,
  EDUCATION,
  COURSEWORK,
  ACHIEVEMENTS,
  CONTACT,
} from '@/content/aryan';

export {
  ARYAN_PROFILE,
  PORTFOLIO_INFO,
  PROJECTS_DATA,
  NOTES_DATA,
  SKILLS_CATEGORIZED,
  RESUME_PROJECTS,
  RESUME_PROJECT_IDS,
  EDUCATION,
  COURSEWORK,
  ACHIEVEMENTS,
  CONTACT,
};
