import fs from 'fs';
import path from 'path';
import { scanProjects, PROJECTS_CONTENT_DIR } from '../lib/getProjects';

const PUBLIC_PROJECTS_DIR = path.join(process.cwd(), 'public', 'projects');
const GENERATED_OUTPUT = path.join(process.cwd(), 'lib', 'projects.generated.ts');

const IMAGE_EXT = /\.(png|jpe?g)$/i;
const PDF_EXT = /\.pdf$/i;

function copyProjectAssets(slug: string): void {
  const srcDir = path.join(PROJECTS_CONTENT_DIR, slug);
  const destDir = path.join(PUBLIC_PROJECTS_DIR, slug);
  fs.mkdirSync(destDir, { recursive: true });

  const assets = fs
    .readdirSync(srcDir)
    .filter((name) => IMAGE_EXT.test(name) || PDF_EXT.test(name));

  for (const name of assets) {
    fs.copyFileSync(path.join(srcDir, name), path.join(destDir, name));
  }
}

function emitGeneratedModule(projectsJson: string): void {
  const source = `// AUTO-GENERATED by scripts/generate-projects.ts — DO NOT EDIT.
// Regenerated automatically on every \`npm run dev\` and \`npm run build\`.
import type { ProjectFolder } from '../types/mac';

export const GENERATED_PROJECTS: ProjectFolder[] = ${projectsJson};
`;
  const tmp = `${GENERATED_OUTPUT}.tmp`;
  fs.writeFileSync(tmp, source, 'utf8');
  fs.renameSync(tmp, GENERATED_OUTPUT);
}

function main(): void {
  const projects = scanProjects();

  fs.rmSync(PUBLIC_PROJECTS_DIR, { recursive: true, force: true });
  fs.mkdirSync(PUBLIC_PROJECTS_DIR, { recursive: true });

  for (const project of projects) {
    copyProjectAssets(project.id);
  }

  emitGeneratedModule(JSON.stringify(projects, null, 2));

  const assetCount = projects.reduce(
    (acc, p) => acc + p.files.filter((f) => f.imageUrl || f.pdfUrl).length,
    0
  );
  console.log(
    `[generate-projects] Generated ${projects.length} project(s) -> lib/projects.generated.ts`
  );
  console.log(
    `[generate-projects] Copied ${assetCount} image/pdf asset(s) -> public/projects/`
  );
}

main();
