import fs from 'fs';
import path from 'path';
import { scanProjects, PROJECTS_CONTENT_DIR } from '../lib/getProjects';
import { syncAssets } from '../lib/syncAssets';

const PUBLIC_PROJECTS_DIR = path.join(process.cwd(), 'public', 'projects');
const GENERATED_OUTPUT = path.join(process.cwd(), 'lib', 'projects.generated.ts');

const IMAGE_EXT = /\.(png|jpe?g)$/i;
const PDF_EXT = /\.pdf$/i;
const ASSET_EXT = (name: string) => IMAGE_EXT.test(name) || PDF_EXT.test(name);

function buildGeneratedModule(projectsJson: string): string {
  return `// AUTO-GENERATED by scripts/generate-projects.ts — DO NOT EDIT.
// Regenerated automatically on every \`npm run dev\` and \`npm run build\`.
import type { ProjectFolder } from '../types/mac';

export const GENERATED_PROJECTS: ProjectFolder[] = ${projectsJson};
`;
}

function main(): void {
  const projects = scanProjects();
  const assetCount = projects.reduce(
    (acc, p) => acc + p.files.filter((f) => f.imageUrl || f.pdfUrl).length,
    0
  );

  const sync = syncAssets({
    srcDir: PROJECTS_CONTENT_DIR,
    destDir: PUBLIC_PROJECTS_DIR,
    filter: ASSET_EXT,
  });

  if (sync.skipped) {
    console.warn(`[generate-projects] WARNING: ${sync.reason}`);
  } else {
    console.log(
      `[generate-projects] Synced public/projects/ (${projects.length} project(s), ${assetCount} asset(s)): ${sync.added} added, ${sync.updated} updated, ${sync.stale} stale removed`
    );
  }

  const source = buildGeneratedModule(JSON.stringify(projects, null, 2));
  const moduleChanged =
    !fs.existsSync(GENERATED_OUTPUT) ||
    fs.readFileSync(GENERATED_OUTPUT, 'utf8') !== source;
  if (moduleChanged) {
    const tmp = `${GENERATED_OUTPUT}.tmp`;
    fs.writeFileSync(tmp, source, 'utf8');
    fs.renameSync(tmp, GENERATED_OUTPUT);
  }

  if (!moduleChanged && sync.added === 0 && sync.updated === 0 && sync.stale === 0) return;

  console.log(
    `[generate-projects] Generated ${projects.length} project(s) -> lib/projects.generated.ts`
  );
}

main();
