import fs from 'fs';
import path from 'path';
import { scanDocuments, DOCUMENTS_CONTENT_DIR } from '../lib/getDocuments';
import { syncAssets } from '../lib/syncAssets';

const PUBLIC_DOCUMENTS_DIR = path.join(process.cwd(), 'public', 'documents');
const GENERATED_OUTPUT = path.join(process.cwd(), 'lib', 'documents.generated.ts');

const PDF_EXT = /\.pdf$/i;

function buildGeneratedModule(documentsJson: string): string {
  return `// AUTO-GENERATED by scripts/generate-documents.ts — DO NOT EDIT.
// Regenerated automatically on every \`npm run dev\` and \`npm run build\`.
import type { FileItem } from '../types/mac';

export const GENERATED_DOCUMENTS: FileItem[] = ${documentsJson};
`;
}

function main(): void {
  const documents = scanDocuments();

  const sync = syncAssets({
    srcDir: DOCUMENTS_CONTENT_DIR,
    destDir: PUBLIC_DOCUMENTS_DIR,
    filter: (name) => PDF_EXT.test(name),
  });

  if (sync.skipped) {
    console.warn(`[generate-documents] WARNING: ${sync.reason}`);
  } else {
    console.log(
      `[generate-documents] Synced public/documents/ (${documents.length} document(s)): ${sync.added} added, ${sync.updated} updated, ${sync.stale} stale removed`
    );
  }

  const source = buildGeneratedModule(JSON.stringify(documents, null, 2));
  const moduleChanged =
    !fs.existsSync(GENERATED_OUTPUT) ||
    fs.readFileSync(GENERATED_OUTPUT, 'utf8') !== source;
  if (moduleChanged) {
    const tmp = `${GENERATED_OUTPUT}.tmp`;
    fs.writeFileSync(tmp, source, 'utf8');
    fs.renameSync(tmp, GENERATED_OUTPUT);
  }

  if (!moduleChanged && sync.added === 0 && sync.updated === 0 && sync.stale === 0) return;

  console.log(
    `[generate-documents] Generated ${documents.length} document(s) -> lib/documents.generated.ts`
  );
}

main();
