import fs from 'fs';
import path from 'path';
import { scanResearch, RESEARCH_CONTENT_DIR } from '../lib/getResearch';
import { syncAssets } from '../lib/syncAssets';

const PUBLIC_RESEARCH_DIR = path.join(process.cwd(), 'public', 'research');
const GENERATED_OUTPUT = path.join(process.cwd(), 'lib', 'research.generated.ts');

const ASSET_EXT = /\.(png|jpe?g|pdf)$/i;

function buildGeneratedModule(researchJson: string): string {
  return `// AUTO-GENERATED by scripts/generate-research.ts — DO NOT EDIT.
// Regenerated automatically on every \`npm run dev\` and \`npm run build\`.
import type { ResearchFolder } from '../types/mac';

export const GENERATED_RESEARCH: ResearchFolder[] = ${researchJson};
`;
}

function main(): void {
  const topics = scanResearch();

  const sync = syncAssets({
    srcDir: RESEARCH_CONTENT_DIR,
    destDir: PUBLIC_RESEARCH_DIR,
    filter: (name) => ASSET_EXT.test(name),
  });

  if (sync.skipped) {
    if (topics.length > 0) {
      // Topics can be README-only — no binary assets to copy. Not an error.
      console.log(
        `[generate-research] ${topics.length} topic(s) are README-only (no images/PDFs to sync).`
      );
    } else {
      console.warn(`[generate-research] WARNING: ${sync.reason}`);
    }
  } else {
    console.log(
      `[generate-research] Synced public/research/ (${topics.length} topic(s)): ${sync.added} added, ${sync.updated} updated, ${sync.stale} stale removed`
    );
  }

  const source = buildGeneratedModule(JSON.stringify(topics, null, 2));
  const moduleChanged =
    !fs.existsSync(GENERATED_OUTPUT) ||
    fs.readFileSync(GENERATED_OUTPUT, 'utf8') !== source;
  if (moduleChanged) {
    const tmp = `${GENERATED_OUTPUT}.tmp`;
    fs.writeFileSync(tmp, source, 'utf8');
    fs.renameSync(tmp, GENERATED_OUTPUT);
  }

  if (!moduleChanged && sync.added === 0 && sync.updated === 0 && sync.stale === 0) return;

  console.log(
    `[generate-research] Generated ${topics.length} topic(s) -> lib/research.generated.ts`
  );
}

main();
